<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Broiler.App.Android</RootNamespace>
    <AssemblyName>Broiler.App.Android</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Broiler.Graphics" />
    <PackageReference Include="Broiler.Input.Android" />
    <PackageReference Include="Broiler.Input.Keyboard.Android" />
    <PackageReference Include="Broiler.Input.Pen.Android" />
    <PackageReference Include="Broiler.Input.Text.Android" />
    <PackageReference Include="Broiler.Input.Touch.Android" />
    <PackageReference Include="Broiler.UI" />
  </ItemGroup>

</Project>
